blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/DmitryNasikanov/infinite-energy/discussions
    about: Ask questions or discuss ideas before filing an issue
